const KEY = 'ltzb-alliance-ledger-v1';
const $ = id => document.getElementById(id);
const state = JSON.parse(localStorage.getItem(KEY) || '{"season":"征服赛季 · 待命名","members":[],"records":[]}');
const number = v => Math.max(0, Number(v) || 0);
const fmt = n => number(n).toLocaleString('zh-CN');
const nowLocal = () => { const d=new Date(); d.setMinutes(d.getMinutes()-d.getTimezoneOffset()); return d.toISOString().slice(0,16) };

function save(){ state.season = $('seasonName').value.trim() || '未命名赛季'; localStorage.setItem(KEY, JSON.stringify(state)); render(); }
function toast(message){ const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),2200); }
function getMember(id){ return state.members.find(m=>m.id===id); }
function totals(id){ const records=state.records.filter(r=>r.memberId===id); return records.reduce((a,r)=>({merit:a.merit+number(r.merit),kills:a.kills+number(r.kills),losses:a.losses+number(r.losses),demo:a.demo+number(r.demo),garrison:a.garrison+number(r.garrison),support:a.support+number(r.support),key:a.key+(r.type==='key'?1:0)}),{merit:0,kills:0,losses:0,demo:0,garrison:0,support:0,key:0}); }
function profile(m){ const t=totals(m.id); const attendance=m.required ? Math.min(100, Math.round(m.attended/m.required*100)) : 100; return {...m,...t,attendance}; }
function scored(){ const ps=state.members.map(profile); const max=k=>Math.max(1,...ps.map(x=>number(x[k]))); const mx={merit:max('merit'),kills:max('kills'),demo:max('demo'),garrison:max('garrison'),support:max('support'),power:max('power'),teams:max('teams'),baseDemo:max('baseDemo')}; return ps.map(p=>{ const war=(p.merit/mx.merit*.75+p.kills/mx.kills*.25)*35; const siege=(p.demo/mx.demo*.82+Math.min(1,p.key/3)*.18)*25; const execution=(p.attendance*.7+number(p.orders)*.3)/100*20; const development=(p.power/mx.power*.5+p.teams/mx.teams*.3+p.baseDemo/mx.baseDemo*.2)*10; const support=(p.support/mx.support*.7+p.garrison/mx.garrison*.3)*10; const score=Math.max(0,war+siege+execution+development+support+Number(p.discipline)); const grade=score>=80?'A':score>=60?'B':score>=40?'C':'D'; return {...p,score:Math.round(score*10)/10,grade}; }).sort((a,b)=>b.score-a.score); }
function gradeBadge(g){ return `<span class="grade grade-${g}">${g}</span>`; }
function empty(message){return `<div class="empty">${message}</div>`}
function renderDashboard(players){ const all=state.records.reduce((a,r)=>({merit:a.merit+number(r.merit),demo:a.demo+number(r.demo)}),{merit:0,demo:0}); $('memberCount').textContent=state.members.length; $('totalMerit').textContent=fmt(all.merit); $('totalDemo').textContent=fmt(all.demo); const active=players.filter(p=>p.required>0); $('avgAttendance').textContent=active.length ? Math.round(active.reduce((a,p)=>a+p.attendance,0)/active.length)+'%' : '—'; $('ranking').innerHTML=players.length?players.slice(0,10).map((p,i)=>`<div class="rank-row"><div class="rank-number ${i<3?'top':''}">0${i+1}</div><div><span class="player-name">${safe(p.name)}</span><span class="player-meta">${safe(p.group)} · ${safe(p.role)} · 武勋 ${fmt(p.merit)}</span></div><div class="bar-wrap"><div class="bar"><i style="width:${Math.min(100,p.score)}%"></i></div></div><div class="rank-score">${p.score}</div>${gradeBadge(p.grade)}</div>`).join(''):empty('先在“盟员档案”新增成员，再开始录入战报。'); const alerts=[]; players.forEach(p=>{if(p.required>0&&p.attendance<70) alerts.push(`<div class="alert"><i class="alert-dot"></i><div><b>${safe(p.name)}</b><span>本周到场率 ${p.attendance}% ，建议确认排班或现实原因。</span></div></div>`); if(Number(p.discipline)<0) alerts.push(`<div class="alert"><i class="alert-dot" style="background:var(--red)"></i><div><b>${safe(p.name)}</b><span>存在纪律扣分（${p.discipline}），请结合管理备注复核。</span></div></div>`)}); $('alerts').innerHTML=alerts.length?alerts.slice(0,5).join(''):empty('暂无需要特别跟进的情况。'); }
function renderMembers(players){ const q=$('memberSearch').value.trim().toLowerCase(); const filtered=players.filter(p=>[p.name,p.group,p.role].join(' ').toLowerCase().includes(q)); $('memberSummary').textContent=`${filtered.length} 名盟员`; $('memberTable').innerHTML=filtered.length?filtered.map(p=>`<tr><td><span class="table-name">${safe(p.name)}</span><br><span class="muted">${safe(p.notes||'—')}</span></td><td>${safe(p.group)}<br><span class="muted">${safe(p.role)}</span></td><td>${fmt(p.power)}</td><td>${fmt(p.merit)}</td><td>${fmt(p.demo)}</td><td>${p.attendance}%</td><td><b>${p.score}</b></td><td>${gradeBadge(p.grade)}</td><td><button class="link-button" data-edit="${p.id}">编辑</button></td></tr>`).join(''):empty('还没有盟员档案。'); }
function typeName(t){return ({combat:'战斗',siege:'攻城',key:'关键战',logistics:'后勤'})[t]||t}
function renderRecords(){ const member=$('recordFilterMember').value, type=$('recordFilterType').value; const rs=state.records.filter(r=>(!member||r.memberId===member)&&(!type||r.type===type)).sort((a,b)=>new Date(b.date)-new Date(a.date)); $('recordSummary').textContent=`${rs.length} 条记录`; $('recordTable').innerHTML=rs.length?rs.map(r=>`<tr><td>${r.date?new Date(r.date).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}</td><td class="table-name">${safe(getMember(r.memberId)?.name||'已删除盟员')}</td><td>${typeName(r.type)}</td><td>${safe(r.title||'—')}<br><span class="muted">${safe(r.notes||'')}</span></td><td>${fmt(r.merit)}</td><td>${fmt(r.kills)}</td><td>${fmt(r.demo)}</td><td>${fmt(r.garrison+r.support)}</td><td><button class="link-button delete" data-delete-record="${r.id}">删除</button></td></tr>`).join(''):empty('还没有贡献记录。'); }
function renderSelects(){ const selected=$('recordMember').value, filter=$('recordFilterMember').value; const options=state.members.map(m=>`<option value="${m.id}">${safe(m.name)} · ${safe(m.group)}</option>`).join(''); $('recordMember').innerHTML=`<option value="">请选择盟员</option>${options}`; $('recordMember').value=selected; $('recordFilterMember').innerHTML=`<option value="">全部盟员</option>${options}`; $('recordFilterMember').value=filter; }
function render(){ $('seasonName').value=state.season||''; const ps=scored(); renderSelects(); renderDashboard(ps); renderMembers(ps); renderRecords(); }
function safe(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML}
function showView(id){document.querySelectorAll('.view,.tabs button').forEach(e=>e.classList.remove('active')); $(id).classList.add('active'); document.querySelector(`.tabs button[data-view="${id}"]`)?.classList.add('active');}
function openEditor(m){
  $('memberEditor').classList.remove('hidden');
  $('editorTitle').textContent=m?'编辑盟员':'新增盟员';
  const vals=m||{id:'',name:'',group:'主战团',role:'主战',power:0,teams:0,baseDemo:0,required:0,attended:0,orders:100,discipline:0,notes:''};
  const fields={id:'editMemberId',name:'memberName',group:'memberGroup',role:'memberRole',power:'memberPower',teams:'memberTeams',baseDemo:'memberBaseDemo',required:'memberRequired',attended:'memberAttended',orders:'memberOrders',discipline:'memberDiscipline',notes:'memberNotes'};
  Object.entries(fields).forEach(([key,id])=>$(id).value=vals[key]??'');
  $('memberName').focus();
}

document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('seasonName').addEventListener('change',save); $('memberSearch').addEventListener('input',()=>renderMembers(scored())); $('recordFilterMember').addEventListener('change',renderRecords); $('recordFilterType').addEventListener('change',renderRecords); $('clearFilters').onclick=()=>{$('recordFilterMember').value='';$('recordFilterType').value='';renderRecords()};
$('addMember').onclick=()=>openEditor(); $('closeEditor').onclick=()=>$('memberEditor').classList.add('hidden');
$('memberForm').addEventListener('submit',e=>{e.preventDefault();const id=$('editMemberId').value||crypto.randomUUID();const m={id,name:$('memberName').value.trim(),group:$('memberGroup').value,role:$('memberRole').value,power:number($('memberPower').value),teams:number($('memberTeams').value),baseDemo:number($('memberBaseDemo').value),required:number($('memberRequired').value),attended:number($('memberAttended').value),orders:number($('memberOrders').value),discipline:Number($('memberDiscipline').value),notes:$('memberNotes').value.trim()};const i=state.members.findIndex(x=>x.id===id);if(i<0)state.members.push(m);else state.members[i]=m;$('memberEditor').classList.add('hidden');save();toast('盟员档案已保存');});
document.addEventListener('click',e=>{const edit=e.target.dataset.edit, del=e.target.dataset.deleteRecord;if(edit)openEditor(getMember(edit));if(del){state.records=state.records.filter(r=>r.id!==del);save();toast('贡献记录已删除')}});
$('recordForm').addEventListener('submit',e=>{e.preventDefault();if(!$('recordMember').value){toast('请先选择对应盟员');return}state.records.push({id:crypto.randomUUID(),memberId:$('recordMember').value,type:$('recordType').value,date:$('recordDate').value,title:$('recordTitle').value.trim(),merit:number($('recordMerit').value),kills:number($('recordKills').value),losses:number($('recordLosses').value),demo:number($('recordDemo').value),garrison:number($('recordGarrison').value),support:number($('recordSupport').value),notes:$('recordNotes').value.trim()}); e.target.reset();$('recordDate').value=nowLocal();save();toast('战报已计入盟员统计');});
function setImage(file){if(!file)return;if(!file.type.startsWith('image/')){toast('请选择图片文件');return}const url=URL.createObjectURL(file);$('preview').src=url;$('preview').classList.remove('hidden');$('runOcr').disabled=false;$('ocrStatus').textContent=`已选择：${file.name}。点击“开始识别”。`;}
$('chooseImage').onclick=()=>$('imageInput').click(); $('imageInput').onchange=e=>setImage(e.target.files[0]); const dz=$('dropZone');['dragenter','dragover'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.style.borderColor='var(--gold)'}));['dragleave','drop'].forEach(n=>dz.addEventListener(n,e=>{e.preventDefault();dz.style.borderColor='';}));dz.addEventListener('drop',e=>setImage(e.dataTransfer.files[0]));
$('runOcr').onclick=async()=>{if(!window.Tesseract){$('ocrStatus').textContent='识别组件未加载。请检查网络，或直接粘贴文字手动提取。';return}try{$('runOcr').disabled=true;$('ocrStatus').textContent='正在识别中文文字，请稍候…';const result=await Tesseract.recognize($('preview').src,'chi_sim+eng',{logger:m=>{if(m.status==='recognizing text')$('ocrStatus').textContent=`正在识别：${Math.round(m.progress*100)}%`}});$('ocrText').value=result.data.text;$('ocrStatus').textContent='识别完成。请核对字段后保存。';parseText();}catch(err){$('ocrStatus').textContent='识别失败：可直接粘贴文字并手动填写字段。';}finally{$('runOcr').disabled=false}};
function extract(text,labels){for(const l of labels){const r=new RegExp(l+'[：:\\s]*([0-9,，]+)','i');const m=text.match(r);if(m)return number(m[1].replace(/[,，]/g,''));}return 0}
function parseText(){const t=$('ocrText').value; $('recordMerit').value=extract(t,['武勋','战功']);$('recordKills').value=extract(t,['杀敌','歼敌','击杀']);$('recordLosses').value=extract(t,['战损','损失']);$('recordDemo').value=extract(t,['拆迁','拆除','耐久削减']);const title=t.match(/(?:城池|关卡|战役|目标)[：:\s]*([^\n]{2,20})/);if(title)$('recordTitle').value=title[1].trim();toast('已从文字尝试提取数字，请逐项核对。')}
$('parseText').onclick=parseText; $('recordDate').value=nowLocal();
$('exportBtn').onclick=()=>{save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`率土同盟台账-${(state.season||'赛季').replace(/[\\/:*?"<>|]/g,'_')}.json`;a.click();URL.revokeObjectURL(a.href);toast('数据已导出')};
$('importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const v=JSON.parse(await f.text());if(!Array.isArray(v.members)||!Array.isArray(v.records))throw Error();state.season=v.season||state.season;state.members=v.members;state.records=v.records;save();toast('数据已导入');}catch{toast('导入失败：请选择本网站导出的 JSON 数据文件')}e.target.value=''};
render();
